-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 08:24:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image_url` VARCHAR(255) NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `role` ENUM('ADMINISTRATOR', 'COORDINATOR', 'MONITOR', 'STUDENT') NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_accounts_unique` (`email` ASC) VISIBLE,
  CONSTRAINT chk_accounts_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administrators_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `email_administrators_unique` (`email` ASC) VISIBLE,
  UNIQUE INDEX `account_id_administrators_unique` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_administrators_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT chk_administrators_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coordinators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coordinators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_coordinators_unique` (`email` ASC) VISIBLE,
  INDEX `fk_coordinators_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_coordinators_unique` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_coordinators_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT chk_coordinators_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`monitors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_monitors_unique` (`email` ASC) VISIBLE,
  INDEX `fk_monitors_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_monitors_unique` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_monitors_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT chk_monitors_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `phone` VARCHAR(25) NULL,
  `image_url` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_schools_unique` (`cnpj` ASC) VISIBLE,
  INDEX `fk_schools_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_schools_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT chk_schools_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `shift` ENUM('MORNING', 'AFTERNOON', 'EVENING', 'NIGHT') NOT NULL,
  `academic_year` VARCHAR(6) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `school_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classes_school_idx` (`school_id` ASC) VISIBLE,
  INDEX `fk_classes_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`announcements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `announcement_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_announcements_class_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_announcements_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_announcements_announcement_idx` (`announcement_id` ASC) VISIBLE,
  CONSTRAINT `fk_announcements_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcements_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_announcements_announcement_id`
    FOREIGN KEY (`announcement_id`)
    REFERENCES `mydb`.`announcements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lesson_plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `objectives` TEXT NOT NULL,
  `materials` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_plans_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_plans_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `lesson_plan_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lessons_lesson_plan_idx` (`lesson_plan_id` ASC) VISIBLE,
  UNIQUE INDEX `lesson_plan_id_lessons_unique` (`lesson_plan_id` ASC) VISIBLE,
  INDEX `fk_lessons_class_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_lessons_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_lessons_lesson_plan_id`
    FOREIGN KEY (`lesson_plan_id`)
    REFERENCES `mydb`.`lesson_plans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lesson_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lesson_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  `lesson_comment_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_comments_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_lesson_comments_lesson_idx` (`lesson_id` ASC) VISIBLE,
  INDEX `fk_lesson_comments_lesson_comment_idx` (`lesson_comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_lesson_comments_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lesson_comments_lesson_id`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lessons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lesson_comments_lesson_comment_id`
    FOREIGN KEY (`lesson_comment_id`)
    REFERENCES `mydb`.`lesson_comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `enrollment` VARCHAR(25) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NULL,
  `school_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_students_unique` (`email` ASC) VISIBLE,
  INDEX `fk_students_account_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `enrollment_students_unique` (`enrollment` ASC) VISIBLE,
  UNIQUE INDEX `account_id_students_unique` (`account_id` ASC) VISIBLE,
  INDEX `fk_students_school_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT chk_students_email_format CHECK (`email` LIKE '%@%.%'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attendances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attendances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_present` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `student_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attendances_student_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_attendances_lesson_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_attendances_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendances_lesson_id`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `mydb`.`lessons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT chk_attendances_is_present CHECK (`is_present` IN (0, 1)))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `max_score` DECIMAL(4,2) NOT NULL,
  `due_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_activities_class_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_activities_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activities_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` DECIMAL(4,2) NOT NULL DEFAULT 0,
  `submitted` TINYINT(1) NOT NULL DEFAULT 0,
  `submission_date` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `student_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_activities_student_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_student_activities_activity_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_activities_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_activities_activity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activities` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT chk_student_activities_submitted CHECK (`submitted` IN (0, 1)))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activity_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activity_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `activity_comment_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_comments_activity_idx` (`activity_id` ASC) VISIBLE,
  INDEX `fk_activity_comments_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_activity_comments_activity_comment_idx` (`activity_comment_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_comments_activity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_comments_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_comments_activity_comment_id`
    FOREIGN KEY (`activity_comment_id`)
    REFERENCES `mydb`.`activity_comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `student_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_class_students_student_id_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_class_students_class_id_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_student_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_student_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`class_teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`class_teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `account_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_class_teachers_account_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_class_teachers_class_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_teachers_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_teachers_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`accounts_BEFORE_INSERT` BEFORE INSERT ON `accounts` FOR EACH ROW
BEGIN
  IF NEW.role = 'ADMINISTRATOR' THEN
    SET NEW.role_id = (SELECT `id` FROM `mydb`.`administrators` WHERE `email` = NEW.email);
  ELSEIF NEW.role = 'COORDINATOR' THEN
    SET NEW.role_id = (SELECT `id` FROM `mydb`.`coordinators` WHERE `email` = NEW.email);
  ELSEIF NEW.role = 'MONITOR' THEN
    SET NEW.role_id = (SELECT `id` FROM `mydb`.`monitors` WHERE `email` = NEW.email);
  ELSEIF NEW.role = 'STUDENT' THEN
    SET NEW.role_id = (SELECT `id` FROM `mydb`.`students` WHERE `email` = NEW.email);
  END IF;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`accounts_AFTER_INSERT` AFTER INSERT ON `accounts` FOR EACH ROW
BEGIN
  IF NEW.role = 'ADMINISTRATOR' THEN
    UPDATE `mydb`.`administrators`
    SET `account_id` = NEW.id
    WHERE `id` = NEW.role_id;
  ELSEIF NEW.role = 'COORDINATOR' THEN
    UPDATE `mydb`.`coordinators`
    SET `account_id` = NEW.id
    WHERE `id` = NEW.role_id;
  ELSEIF NEW.role = 'MONITOR' THEN
    UPDATE `mydb`.`monitors`
    SET `account_id` = NEW.id
    WHERE `id` = NEW.role_id;
  ELSEIF NEW.role = 'STUDENT' THEN
    UPDATE `mydb`.`students`
    SET `account_id` = NEW.id
    WHERE `id` = NEW.role_id;
  END IF;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`lessons_AFTER_INSERT` AFTER INSERT ON `lessons` FOR EACH ROW
BEGIN
  INSERT INTO attendances (student_id, lesson_id)
  SELECT cs.student_id, NEW.id
  FROM `mydb`.`class_students` cs
  WHERE cs.class_id = NEW.class_id;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`activities_AFTER_INSERT` AFTER INSERT ON `activities` FOR EACH ROW
BEGIN
  INSERT INTO student_activities (student_id, activity_id)
  SELECT cs.student_id, NEW.id
  FROM `mydb`.`class_students` cs
  WHERE cs.class_id = NEW.class_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
